name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: install packages
        run: npm install
      - name: install xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: node -v
      - name: Jest Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:jest
        env:
          TEST: ${{ secrets.TEST }}
      - name: Mocha Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:mocha
        env:
          TEST: ${{ secrets.TEST }}